# Uncomment the next line to define a global platform for your project
  platform :ios, '14.4'

target 'CDNewsAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CDNewsAPI
  pod 'SDWebImage'

end
